# Generated by Django 5.2.8 on 2026-05-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_prescription_options_prescription_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='company_name',
            field=models.CharField(default='Healeaf Pharma', max_length=200),
        ),
    ]
